

# URL de Metricas coletada pelo opentelemetry

GET http://localhost:8081/metrics

####

POST http://localhost:8081/api/v1/login HTTP/1.1
Content-Type: application/json

{
    "email": "wagner.oliveira@gmail.com",
    "password": "1234"
}

####


POST http://localhost:8081/api/v1/clients HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndhZ25lci5vbGl2ZWlyYUBnbWFpbC5jb20iLCJleHAiOjE3MDIzOTMzMjMsImlkIjoiNWQ3OTQ2MTItZGZhNi00MDBhLWJkYmUtOWEwNjM2YzM2NzE2Iiwic3ViIjoiNWQ3OTQ2MTItZGZhNi00MDBhLWJkYmUtOWEwNjM2YzM2NzE2In0.XVRhwK8fY07X6aYYNfWvddpkzByM6sMdp9MYsY

{
    "name": "Carla Peres",
    "email": "carla.peres12@gmail.com",
    "password": "1234"

}

###

POST http://localhost:8081/api/v1/accounts HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndhZ25lci5vbGl2ZWlyYUBnbWFpbC5jb20iLCJleHAiOjE3MDIzOTM0MzMsImlkIjoiNWQ3OTQ2MTItZGZhNi00MDBhLWJkYmUtOWEwNjM2YzM2NzE2Iiwic3ViIjoiNWQ3OTQ2MTItZGZhNi00MDBhLWJkYmUtOWEwNjM2YzM2NzE2In0.1JT05b5RWqcAgOZWd6nMINU3AKFMZZ8GVmtDvHis9Ro

{
    "client_id": "d9213628-9238-4118-9237-045c9cf02bd9"
}

###

POST http://localhost:8081/api/v1/transactions HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndhZ25lci5vbGl2ZWlyYUBnbWFpbC5jb20iLCJleHAiOjE3MDIzOTM0MzMsImlkIjoiNWQ3OTQ2MTItZGZhNi00MDBhLWJkYmUtOWEwNjM2YzM2NzE2Iiwic3ViIjoiNWQ3OTQ2MTItZGZhNi00MDBhLWJkYmUtOWEwNjM2YzM2NzE2In0.1JT05b5RWqcAgOZWd6nMINU3AKFMZZ8GVmtDvHis9Ro

{
    "account_id_from": "dc986f54-7756-41a4-9cee-e847c60b5d60",
    "account_id_to": "6ceabb90-9667-4858-8f30-51b858158fea",
    "amount": 10
}