
POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "Wagner",
    "email": "wagner@gmail.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "eb66ba2a-f53b-4ba3-b44a-84a73def3790"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "271ce2a1-d4bb-4345-9104-9299da1c5bb7",
    "account_id_to": "4b9ccac7-f687-4252-8860-ed9e9db4ffc1",
    "amount": 100
}